// <auto-generated />
using System;
using System.Collections.Generic;
using CivicSignal.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace CivicSignal.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CivicSignalDbContext))]
    [Migration("20260724062152_AddDataImportJobs")]
    partial class AddDataImportJobs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CivicSignal.Domain.DataImports.DataImportJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CreatedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("created_count");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("error_message");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("ImportType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("import_type");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("parameters_json");

                    b.Property<int>("ReceivedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("received_count");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<Guid?>("RequestedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by_user_id");

                    b.Property<int>("SkippedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("skipped_count");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UpdatedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("updated_count");

                    b.HasKey("Id");

                    b.HasIndex("RequestedAt")
                        .HasDatabaseName("ix_data_import_jobs_requested_at");

                    b.HasIndex("Source")
                        .HasDatabaseName("ix_data_import_jobs_source");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_data_import_jobs_status");

                    b.HasIndex("Source", "Status", "RequestedAt")
                        .HasDatabaseName("ix_data_import_jobs_source_status_requested_at");

                    b.ToTable("data_import_jobs", (string)null);
                });

            modelBuilder.Entity("CivicSignal.Domain.HistoricalComplaints.HistoricalComplaint", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Agency")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("agency");

                    b.Property<string>("AgencyName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("agency_name");

                    b.Property<string>("Borough")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("borough");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<string>("ComplaintType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("complaint_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Descriptor")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("descriptor");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("external_id");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at");

                    b.Property<string>("IncidentAddress")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("incident_address");

                    b.Property<Point>("LocationPoint")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("geography(point,4326)")
                        .HasColumnName("location")
                        .HasComputedColumnSql("ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography", true);

                    b.Property<string>("ResolutionDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("resolution_description");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Location", "CivicSignal.Domain.HistoricalComplaints.HistoricalComplaint.Location#GeoPoint", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("longitude");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Agency")
                        .HasDatabaseName("ix_historical_complaints_agency");

                    b.HasIndex("Borough")
                        .HasDatabaseName("ix_historical_complaints_borough");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_historical_complaints_category");

                    b.HasIndex("ComplaintType")
                        .HasDatabaseName("ix_historical_complaints_complaint_type");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_historical_complaints_created_at");

                    b.HasIndex("LocationPoint")
                        .HasDatabaseName("ix_historical_complaints_location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("LocationPoint"), "gist");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_historical_complaints_status");

                    b.HasIndex("Source", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ux_historical_complaints_source_external_id");

                    b.ToTable("historical_complaints", (string)null);
                });

            modelBuilder.Entity("CivicSignal.Domain.Incidents.DuplicateCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CandidateIncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_incident_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "SimilarityScore", "CivicSignal.Domain.Incidents.DuplicateCandidate.SimilarityScore#ConfidenceScore", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("Value")
                                .HasColumnType("double precision")
                                .HasColumnName("similarity_score");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CandidateIncidentId");

                    b.HasIndex("IncidentId", "CandidateIncidentId")
                        .IsUnique()
                        .HasDatabaseName("ix_duplicate_candidates_incident_id_candidate_incident_id");

                    b.ToTable("duplicate_candidates", (string)null);
                });

            modelBuilder.Entity("CivicSignal.Domain.Incidents.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool?>("AcceptedPrediction")
                        .HasColumnType("boolean")
                        .HasColumnName("accepted_prediction");

                    b.Property<string>("CorrectedAgencyCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("corrected_agency_code");

                    b.Property<string>("CorrectedCategory")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("corrected_category");

                    b.Property<string>("CorrectedSeverity")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("corrected_severity");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid?>("DuplicateOfIncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("duplicate_of_incident_id");

                    b.Property<Point>("LocationPoint")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("geography(point,4326)")
                        .HasColumnName("location")
                        .HasComputedColumnSql("ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography", true);

                    b.Property<bool>("NotificationAlertsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("notification_alerts_enabled");

                    b.Property<string>("NotificationChannel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasDefaultValue("None")
                        .HasColumnName("notification_channel");

                    b.Property<DateTimeOffset?>("NotificationPreferenceUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("notification_preference_updated_at");

                    b.Property<string>("ReviewDecision")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("review_decision");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("review_note");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.Property<Vector>("TextEmbedding")
                        .HasColumnType("vector(1024)")
                        .HasColumnName("text_embedding");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Location", "CivicSignal.Domain.Incidents.Incident.Location#GeoPoint", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("longitude");
                        });

                    b.HasKey("Id");

                    b.HasIndex("LocationPoint")
                        .HasDatabaseName("ix_incidents_location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("LocationPoint"), "gist");

                    b.HasIndex("TextEmbedding")
                        .HasDatabaseName("ix_incidents_text_embedding_hnsw")
                        .HasAnnotation("Npgsql:StorageParameter:ef_construction", 64)
                        .HasAnnotation("Npgsql:StorageParameter:m", 16);

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("TextEmbedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("TextEmbedding"), new[] { "vector_cosine_ops" });

                    b.ToTable("incidents", (string)null);
                });

            modelBuilder.Entity("CivicSignal.Domain.Incidents.IncidentFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId", "CreatedAt")
                        .HasDatabaseName("ix_incident_feedback_incident_id_created_at");

                    b.ToTable("incident_feedback", null, t =>
                        {
                            t.HasCheckConstraint("ck_incident_feedback_rating_range", "rating >= 1 AND rating <= 5");
                        });
                });

            modelBuilder.Entity("CivicSignal.Domain.Incidents.IncidentMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double?>("AnalysisConfidence")
                        .HasColumnType("double precision")
                        .HasColumnName("analysis_confidence");

                    b.Property<string>("AnalysisError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("analysis_error");

                    b.Property<string>("AnalysisModelName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("analysis_model_name");

                    b.Property<string>("AnalysisModelVersion")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("analysis_model_version");

                    b.Property<long?>("AnalysisProcessingTimeMilliseconds")
                        .HasColumnType("bigint")
                        .HasColumnName("analysis_processing_time_milliseconds");

                    b.Property<string>("AnalysisStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("analysis_status");

                    b.Property<string>("AnalysisSummary")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("analysis_summary");

                    b.Property<DateTimeOffset?>("AnalyzedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("analyzed_at");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DetectedLabels")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("detected_labels");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("file_name");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("media_type");

                    b.Property<string>("StorageUri")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("storage_uri");

                    b.Property<string>("Transcript")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("transcript");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId")
                        .HasDatabaseName("ix_incident_media_incident_id");

                    b.ToTable("incident_media", (string)null);
                });

            modelBuilder.Entity("CivicSignal.Domain.Incidents.IncidentReviewRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool?>("AcceptedPrediction")
                        .HasColumnType("boolean")
                        .HasColumnName("accepted_prediction");

                    b.Property<string>("CorrectedAgencyCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("corrected_agency_code");

                    b.Property<string>("CorrectedCategory")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("corrected_category");

                    b.Property<string>("CorrectedSeverity")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("corrected_severity");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("decision");

                    b.Property<Guid?>("DuplicateOfIncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("duplicate_of_incident_id");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("note");

                    b.Property<Guid>("ReviewerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewer_user_id");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId", "CreatedAt")
                        .HasDatabaseName("ix_incident_review_records_incident_id_created_at");

                    b.ToTable("incident_review_records", (string)null);
                });

            modelBuilder.Entity("CivicSignal.Domain.Incidents.IncidentUpdateRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("message");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId", "CreatedAt")
                        .HasDatabaseName("ix_incident_update_requests_incident_id_created_at");

                    b.ToTable("incident_update_requests", (string)null);
                });

            modelBuilder.Entity("CivicSignal.Domain.Incidents.PredictionEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double?>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("detail");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("kind");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("title");

                    b.Property<Guid>("TriagePredictionId")
                        .HasColumnType("uuid")
                        .HasColumnName("triage_prediction_id");

                    b.HasKey("Id");

                    b.HasIndex("TriagePredictionId", "CreatedAt")
                        .HasDatabaseName("ix_prediction_evidence_triage_prediction_id_created_at");

                    b.ToTable("prediction_evidence", (string)null);
                });

            modelBuilder.Entity("CivicSignal.Domain.Incidents.ProcessingStep", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_incident_processing_steps_incident_id_name");

                    b.ToTable("incident_processing_steps", (string)null);
                });

            modelBuilder.Entity("CivicSignal.Domain.Incidents.TriagePrediction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("model_name");

                    b.Property<string>("ModelVersion")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("model_version");

                    b.Property<long?>("ProcessingTimeMilliseconds")
                        .HasColumnType("bigint")
                        .HasColumnName("processing_time_ms");

                    b.Property<string>("PromptVersion")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("prompt_version");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("severity");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("summary");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Category", "CivicSignal.Domain.Incidents.TriagePrediction.Category#IncidentCategory", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)")
                                .HasColumnName("category");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Confidence", "CivicSignal.Domain.Incidents.TriagePrediction.Confidence#ConfidenceScore", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("Value")
                                .HasColumnType("double precision")
                                .HasColumnName("confidence");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "SuggestedAgency", "CivicSignal.Domain.Incidents.TriagePrediction.SuggestedAgency#AgencyCode", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("suggested_agency_code");
                        });

                    b.HasKey("Id");

                    b.HasIndex("IncidentId", "CreatedAt")
                        .HasDatabaseName("ix_triage_predictions_incident_id_created_at");

                    b.ToTable("triage_predictions", (string)null);
                });

            modelBuilder.Entity("CivicSignal.Infrastructure.Identity.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("identity_roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            ConcurrencyStamp = "11111111-1111-1111-1111-111111111111",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            ConcurrencyStamp = "22222222-2222-2222-2222-222222222222",
                            Name = "Operator",
                            NormalizedName = "OPERATOR"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            ConcurrencyStamp = "33333333-3333-3333-3333-333333333333",
                            Name = "Reviewer",
                            NormalizedName = "REVIEWER"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            ConcurrencyStamp = "44444444-4444-4444-4444-444444444444",
                            Name = "Reporter",
                            NormalizedName = "REPORTER"
                        });
                });

            modelBuilder.Entity("CivicSignal.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("identity_users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("identity_role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("identity_user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("identity_user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("identity_user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("identity_user_tokens", (string)null);
                });

            modelBuilder.Entity("CivicSignal.Domain.Incidents.DuplicateCandidate", b =>
                {
                    b.HasOne("CivicSignal.Domain.Incidents.Incident", null)
                        .WithMany()
                        .HasForeignKey("CandidateIncidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CivicSignal.Domain.Incidents.Incident", null)
                        .WithMany("DuplicateCandidates")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CivicSignal.Domain.Incidents.IncidentFeedback", b =>
                {
                    b.HasOne("CivicSignal.Domain.Incidents.Incident", null)
                        .WithMany("FeedbackItems")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CivicSignal.Domain.Incidents.IncidentMedia", b =>
                {
                    b.HasOne("CivicSignal.Domain.Incidents.Incident", null)
                        .WithMany("MediaItems")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CivicSignal.Domain.Incidents.IncidentReviewRecord", b =>
                {
                    b.HasOne("CivicSignal.Domain.Incidents.Incident", null)
                        .WithMany("ReviewRecords")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CivicSignal.Domain.Incidents.IncidentUpdateRequest", b =>
                {
                    b.HasOne("CivicSignal.Domain.Incidents.Incident", null)
                        .WithMany("UpdateRequests")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CivicSignal.Domain.Incidents.PredictionEvidence", b =>
                {
                    b.HasOne("CivicSignal.Domain.Incidents.TriagePrediction", null)
                        .WithMany("EvidenceItems")
                        .HasForeignKey("TriagePredictionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CivicSignal.Domain.Incidents.ProcessingStep", b =>
                {
                    b.HasOne("CivicSignal.Domain.Incidents.Incident", null)
                        .WithMany("ProcessingSteps")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CivicSignal.Domain.Incidents.TriagePrediction", b =>
                {
                    b.HasOne("CivicSignal.Domain.Incidents.Incident", null)
                        .WithMany("TriagePredictions")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("CivicSignal.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("CivicSignal.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("CivicSignal.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("CivicSignal.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CivicSignal.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("CivicSignal.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CivicSignal.Domain.Incidents.Incident", b =>
                {
                    b.Navigation("DuplicateCandidates");

                    b.Navigation("FeedbackItems");

                    b.Navigation("MediaItems");

                    b.Navigation("ProcessingSteps");

                    b.Navigation("ReviewRecords");

                    b.Navigation("TriagePredictions");

                    b.Navigation("UpdateRequests");
                });

            modelBuilder.Entity("CivicSignal.Domain.Incidents.TriagePrediction", b =>
                {
                    b.Navigation("EvidenceItems");
                });
#pragma warning restore 612, 618
        }
    }
}
