namespace CivicSignal.Application.Incidents.Models;

public sealed record IncidentDto(
    Guid Id,
    string TrackingCode,
    string Description,
    double Latitude,
    double Longitude,
    string Status,
    DateTimeOffset CreatedAt,
    string? ReviewDecision,
    string? ReviewNote,
    Guid? ReviewedByUserId,
    DateTimeOffset? ReviewedAt,
    string? CorrectedCategory,
    string? CorrectedAgencyCode,
    string? CorrectedSeverity,
    Guid? DuplicateOfIncidentId,
    bool? AcceptedPrediction,
    bool NotificationAlertsEnabled = false,
    string NotificationChannel = "None",
    DateTimeOffset? NotificationPreferenceUpdatedAt = null,
    string? AssignedAgencyCode = null,
    string? AssignedTeam = null,
    Guid? AssignedByUserId = null,
    DateTimeOffset? AssignedAt = null,
    Guid? DispatchedByUserId = null,
    DateTimeOffset? DispatchedAt = null,
    Guid? DuplicateLinkedByUserId = null,
    DateTimeOffset? DuplicateLinkedAt = null);
